### ISSUE TITLE
Error when doing pan gesture 

### ISSUE THREAD

**Issue by hohob28** [micchyboy1023/SimplePhotoViewer#1]
When scroll to images not displayed in list view before in detail view, PhotoCollectionViewCell will be null if you do a pan gesture. 
I have fixed this issue on my side by adding layoutIfNeeded()

May I also fix it for you on the project?

**Comment by masamichiueta** [comment]
Thank you!
Yes, please send me PR!

**Comment by masamichiueta** [comment]
@hohob28  Thank you for your PR👍 I close this issue.
