### ISSUE TITLE
Adjust pop-up zoom back

### ISSUE THREAD

**Issue by gaohomway** [micchyboy1023/SimplePhotoViewer#11]
Hello！

Can I modify the magnification of my photo?

No specific location found.

**Comment by masamichiueta** [comment]
@weifans 
Yes.
You can change it from `ScrollView` in `PhotoZoomViewController` in storyboard.

<img width="1804" alt="screen shot 2019-01-07 at 15 34 26" src="https://user-images.githubusercontent.com/1473923/50752510-e4d17180-1291-11e9-89a5-44005f8ebad8.png">

**Comment by gaohomway** [comment]
@masamichiueta thank you for your reply.
Looks like it is not the answer I want.
Is the slight magnification effect after clicking the photo to open, not the double click to enlarge.

**Comment by masamichiueta** [comment]
@weifans Oh, I understand.
Zoom animation is defined here.
https://github.com/masamichiueta/FluidPhoto/blob/9a3a7aa1896e5955ba255f9822903bfb51543acc/FluidPhoto/Animation/ZoomAnimator.swift#L61

You can change the animation by updating the params.

**Comment by gaohomway** [comment]
@masamichiueta thank you very much

**Comment by masamichiueta** [comment]
You're welcome.
