### ISSUE TITLE
Using with upload image from URL

### ISSUE THREAD

**Issue by Patrashkov** [micchyboy1023/SimplePhotoViewer#14]
Hi,
Possible to use the browser and upload image from URL?
I have issue with different size,  transitionImageView have perfect size. 
ImageView in PhotoZoomViewController when uploaded image  have very big size and incorrect zoom.

**Comment by masamichiueta** [comment]
Hi, 
What do you mean?
Could you attach a gif file?

**Comment by Patrashkov** [comment]
Sorry, i have already fixed.
I forgot recalculate zoomScale for scrollView.
Thank you for the best tutorial and example, good luck

**Comment by masamichiueta** [comment]
@Patrashkov Oh, nice. Thank you for your attention.
