### ISSUE TITLE
Add License?

### ISSUE THREAD

**Issue by walrus-operator** [micchyboy1023/SimplePhotoViewer#3]
Hi there,

This is a great reference project, thanks for putting it out there for people to learn from. I was wondering if you could perhaps add a license file into the repository so people could know by default what your stance is on them using your code in their own projects. Would you consider licensing this under MIT?

Thanks!

**Comment by masamichiueta** [comment]
@inTact700 Thank you for your comment. I added a license file. Please use my project👍

**Comment by walrus-operator** [comment]
@masamichiueta Thanks, much appreciated. Your code has been really helpful!
