### ISSUE TITLE
Double Tap to Zoom When NavigationBar is Displayed

### ISSUE THREAD

**Issue by walrus-operator** [micchyboy1023/SimplePhotoViewer#5]
Hi there,

When you are viewing an image with the UINavigationBar still displayed, if you double tap the image, instead of zooming in it will cause the background to change to black and then require the user to double tap another time to zoom. Do you know of any simple fix to this issue to make it more like the iOS Photos app behavior?

Thanks again for this great example project!

**Comment by masamichiueta** [comment]
@inTact700 Thanks for your report. I fixed the problem in this commit ddf8b8a . Please check it.

**Comment by walrus-operator** [comment]
@masamichiueta That's perfect, thanks for the quick follow-up I appreciate it!
