### ISSUE TITLE
Rotation Bug

### ISSUE THREAD

**Issue by walrus-operator** [micchyboy1023/SimplePhotoViewer#6]
Hi there,

Again thank you for this project!  When rotating the device from portrait to landscape and then back to portrait this causes the imageView frame to be pushed off screen.

Do you have any ideas how to fix this?

Thanks!

**Comment by masamichiueta** [comment]
Checking device rotation event and updating the layout if needed will fix the problem.
Can you make a PR?

**Comment by walrus-operator** [comment]
@masamichiueta I'll try and look into this after work today. I tried quickly overriding viewWillTransition() and calling updateConstraintsForSize() but there seems to be additional modifications required. :confused:

**Comment by masamichiueta** [comment]
Thank you for your trial. I will also check it later, but if you can fix it, please open a PR👍

**Comment by walrus-operator** [comment]
Okay so I've fixed the issue, and although my solution is a little "hacky" it does work as intended. I'll tidy the code tomorrow and submit a PR. :thumbsup:

Thanks again!

**Comment by masamichiueta** [comment]
Nice!
Thank you👍

**Comment by masamichiueta** [comment]
fixed in #7
Thank you!
