### ISSUE TITLE
Cell frame incorrectly calculated after device is rotated

### ISSUE THREAD

**Issue by walrus-operator** [micchyboy1023/SimplePhotoViewer#9]
Hi there,

I've been trying to figure out how to fix this issue with little success and was wondering if you had any ideas.

If you open and close an image without rotating the device, the dismiss animation works well and the CGRect for the collectionView cell is correctly calculated. However, if you rotate the device, open an image, and rotate the device again, the dismiss animation does not work properly (the cell's frame is incorrectly calculated).

I'm pretty sure the issue resides in referenceImageViewFrameInTransitioningView() inside ViewController.swift. For whatever reason the call below returns the incorrect CGRect:

`let cellFrame = self.collectionView.convert(cell.frame, to: self.view)`

Any ideas?

Thanks again!

![issue](https://user-images.githubusercontent.com/12888789/49690721-4b306c00-fafb-11e8-8fca-d3c3df16cafa.gif)

**Comment by walrus-operator** [comment]
I made a lot of progress towards fixing this, and it is almost good to go. I'll probably have a PR for you within the next couple of days. 

Cheers!

**Comment by masamichiueta** [comment]
@inTact700 Wow! Nice👍 Thank you!
